### ISSUE TITLE
Consistent format of task-id

### ISSUE THREAD

**Issue by stephanpelikan** [camunda-community-hub/vanillabp-camunda8-adapter#69]
In Camunda 8 adapter task ids are reported in HEX format as strings. Also completing tasks is based on strings containing HEX formatted task ids. So the Camunda 8 adapter is consistent.

When using Camunda 8 adapter together with Zeebe exporter (e.g. in case of a custom task list application) people have to format task ids, reported by the exporter as long values, into HEX strings. This is not a big deal but typically task ids show up in URLs visible to the user and non-it humans prefer decimal values over HEX values.

Therefor, the formatting of task ids in Camunda 8 adapter should change to decimal instead of HEX per default. To not force people to refactor their existing applications, a Spring Boot configuration has to be introduced overriding the new default format settings on a workflow-module basis:

```yaml
vanillabp:
  workflow-modules:
    Demo:
      adapters:
        camunda8:
          task-id-as-hex-string: true  # default is false
```
